# Generated by Django 2.1.7 on 2019-03-18 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_game_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoveResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wins', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='gamemove',
            name='loses_to',
        ),
        migrations.RemoveField(
            model_name='gamemove',
            name='wins_to',
        ),
        migrations.AddField(
            model_name='moveresult',
            name='against',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='against', to='core.GameMove'),
        ),
        migrations.AddField(
            model_name='moveresult',
            name='game_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.GameType'),
        ),
        migrations.AddField(
            model_name='moveresult',
            name='move',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.GameMove'),
        ),
    ]
